export const quizData = {
  quizTitle: 'Пожарная безопасность',
  quizSynopsis:
    'Давайте проверим ваши знания. Жмите "Начать" чтобы запустить квиз. Удачи!',
  questions: [
    {
      question: 'В банке стал поступать дым, что нужно делать?',
      questionType: 'text',
      questionPic: '/images/02/05.jpg',
      answerSelectionType: 'single',
      answers: [
        'звонить в отдел финансов',
        'звонить в 112',
        'включить пожарную сигнализацию',
        'ждать пока дым сам не пройдет',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно. Так держать!',
      messageForIncorrectAnswer: 'Вы ошиблись. Такое случается.',
      explanation: 'Необходимо в первую очередь сообщить о задымлении.',
      point: '20',
    },
    {
      question: 'Если лестница по пути вниз вся в дыму, что вы будете делать?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'подниматься наверх',
        'пойти в лифт',
        'спускаться вниз сквозь дым',
        'ничего не делать, стоять на пролете, кричать',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Отлично. Впрочем как и всегда.',
      messageForIncorrectAnswer: 'Неверно. Но вы не расстраивайтесь.',
      explanation:
        'Дым поднимается снизу вверх, в такой ситуации лучше всего двигаться как можно ниже.',
      point: '20',
    },
    {
      question: 'Что делать с огнетушителем при пожаре?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'кину огнетушитель  в огонь',
        'ударю чем-то тяжелым по нему',
        'выдерну чеку, нажму на ручку клапана',
        'выдерну чеку, переверну вверх дном, нажму на ручку клапана',
        'накрою огнетушитель тряпкой для вакуума',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Кажется Вам слишком просто.',
      messageForIncorrectAnswer: 'Ошибка это тоже опыт.',
      explanation:
        'Огнетушитель необходимо привести в рабочее состояние выдернув чику и воспользоваться с помощью ручки клапана.',
      point: '10',
    },
    {
      question: 'Если случился ожог, ваша первая помощь?',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'буду обмазывать маслом',
        'буду обмазывать спиртом',
        'буду обмазывать кремом',
        'буду поливать холодной водой',
        'буду растирать снегом - льдом',
      ],
      correctAnswer: [4, 5],
      messageForCorrectAnswer: 'Действительно так. Надеюсь, Вы не угадывали.',
      messageForIncorrectAnswer:
        'Стоит повторить этот материал. У вас обязательно получится',
      explanation: 'Сначала ожог нужно охладить.',
      point: '30',
    },
    {
      question: 'Каким образом лучше потушить горящее масло?',
      questionType: 'photo',
      answerSelectionType: 'single',
      answers: [
        '/images/02/comics-01.jpg',
        '/images/02/comics-02.jpg',
        '/images/02/comics-03.jpg',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верный ответ. Я в Вас не сомневался.',
      messageForIncorrectAnswer: 'Нет, это не так. Но неудачи Вас закаляют.',
      explanation: 'Масло следует накрыть, чтобы перекрыть доступ кислорода.',
      point: '20',
    },
  ],
  appLocale: {
    landingHeaderText: '<questionLength> вопросов',
    question: 'Вопрос',
    startQuizBtn: 'Начать',
    resultFilterAll: 'Все',
    resultFilterCorrect: 'Верно',
    resultFilterIncorrect: 'Неверно',
    nextQuestionBtn: 'Дальше',
    resultPageHeaderText:
      'Ура! Квиз пройден. Вы верно ответили на <correctIndexLength> из <questionLength> вопросов.',
    resultPagePoint: 'Набрано <correctPoints> из <totalPoints> баллов.',
    singleSelectionTagText: 'Один вариант',
    multipleSelectionTagText: 'Несколько вариантов',
    pickNumberOfSelection: 'Выберите <numberOfSelection>',
  },
};
